teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    axis_angular:
      yaw: 0
    scale_linear:
      x: 0.2
    scale_angular:
      yaw: 1.2
    require_enable_button: false
    inverted_reverse: true
    publish_stamped_twist: true
