<?xml version="1.0"?>
<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.13"/>
  <xacro:property name="base_length" value="0.15"/>
  <xacro:property name="base_height" value="0.07"/>

  <xacro:property name="wheel_radius" value="0.028"/>
  <xacro:property name="wheel_width" value="0.0275"/>
  <xacro:property name="wheel_ygap" value="0.002"/>
  <xacro:property name="wheel_zoff" value="-0.01"/>
  <xacro:property name="wheel_xoff" value="0.02"/>

  <xacro:property name="laser_height" value="0.05"/>
  <xacro:property name="laser_radius" value="0.021"/>

  <xacro:property name="caster_xoff" value="0.07"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius+wheel_zoff+base_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff+base_length/2} ${y_reflect*((base_width+wheel_width)/2+wheel_ygap)} ${-wheel_zoff-base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" />

  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="${base_length/3} 0 ${base_height/2 + laser_height/2}" rpy="0 0 0"/>
  </joint>


  <!-- <link name="back_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_caster"/>
    <origin xyz="${base_length/2-caster_xoff} 0.0 ${-wheel_radius-base_height/2}" rpy="0 0 0"/>
  </joint> -->
</robot>
